config/routes.rb
Rails.application.routes.draw do
  resources :transactions, except: [:edit, :update, :show]
  root 'bank#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/transaction.rb
class Transaction < ApplicationRecord

  has_one :cancels_out, class_name: 'Transaction', foreign_key: :cancels_out_id, dependent: :nullify

  validates :amount, presence: true, numericality: true
  # validates :amount, comparison: { greater_than: 0, :less_than_or_equal_to 1000 }
  validates :executor, presence: true
  validates :comment, presence: true

  scope :up_to, ->(date) { where("created_at < ?", date) }

  def self.total(on = Time.now)
    total = 0
    up_to(on).each do |transaction|
      if transaction.deposit
        total += transaction.amount
      else
        total -= transaction.amount
      end
    end
    total
  end

  def self.get_last_five
    candidates = Transaction.includes(:cancels_out).last(10)
    transactions = []
    count = 0
    until candidates.empty? || count == 5
      transaction = candidates.last
      original = transaction.get_original
      transactions << original
      candidates -= [transaction, original]
      count += 1
    end
    return transactions
  end

  def self.last_year_monthly_history
    history = []
    12.times do |index|
      time = index.months.ago
      value =  CreditCalculator.new(DATE_OF_BIRTH, ALLOWANCE, START_DATE, time.to_date).call + Transaction.total(time)
      history << value
    end
    return history
  end

  def get_original
    other_one = self.cancels_out
    return self unless other_one
    return self if self.created_at < other_one.created_at
    return other_one
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bank_controller.rb
class BankController < ApplicationController
  def show
    @credit = CreditCalculator.new(DATE_OF_BIRTH, ALLOWANCE, START_DATE).call + Transaction.total
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  class AuthenticationError < StandardError; end
  class UnprocessableEntity < StandardError; end

  before_action :set_transaction, only: %i[ show destroy ]
  before_action :authenticate, only: :create

  # GET /transactions
  def index
    @transactions = Transaction.get_last_five
    @last_year_monthly_history = Transaction.last_year_monthly_history
    @hide_transactions_menu_item = true
  end

  # GET /transaction/1
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new(transaction_params)
    @deposit = ActiveModel::Type::Boolean.new.cast(transaction_params[:deposit])
  end

  # POST /transactions
  def create
    @transaction = Transaction.new(transaction_params.except(:secret_code))
    raise UnprocessableEntity unless @transaction.save
    redirect_to transactions_url, notice: t(:transaction_created)
  end

  # DELETE /transactions/1
  def destroy
    if @transaction.cancels_out
      other_transaction = @transaction.cancels_out
      if @transaction.created_at > other_transaction.created_at
        @transaction.destroy
        raise UnprocessableEntity unless other_transaction.update(cancels_out: nil)
      else
        other_transaction.destroy
        raise UnprocessableEntity unless @transaction.update(cancels_out: nil)
      end
      redirect_to transactions_url, notice: t(:transaction_restored)

    else
    new_transaction = Transaction.new(
      amount: @transaction.amount,
      cancels_out: @transaction,
      comment: 'Deletes a previous transaction',
      deposit: !@transaction.deposit,
      executor: 'The system'
    )
    raise UnprocessableEntity unless new_transaction.save
    raise UnprocessableEntity unless @transaction.update(cancels_out: new_transaction)
    redirect_to transactions_url, notice: t(:transaction_reverted)
    end
  end

  private

    def authenticate
      raise AuthenticationError unless transaction_params[:secret_code] == ENV["SECRET_CODE"]
    end

    def rescue_unprocessable
      render :index, status: :unprocessable_entity
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(
        :amount,
        :comment,
        :deposit,
        :executor,
        :secret_code
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bank_helper.rb
module BankHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def month_collumn_height_string(monthly_value)
    "height:" + ( (monthly_value / @last_year_monthly_history.max) * 100 ).to_s + "%"
  end
end

app/views/bank/show.html.erb
<div id=credit-container>
  <div id='credit'><%= @credit %> <%= ENV["CURRENCY"]%></div>
  <div id='buttons'>
    <%= button_to t(:withdraw),
                  new_transaction_path,
                  method: :get,
                  params: { transaction: { deposit: false } } %>
    <%= button_to t(:deposit),
                  new_transaction_path,
                  method: :get,
                  params: { transaction: { deposit: true } } %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Piggy bank 2000</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
       <header>
      <nav>
        <%= link_to t(:bank), root_path unless controller_name == "bank" %>
        <%= link_to t(:all_transactions), transactions_path unless @hide_transactions_menu_item %>
      </nav>
    </header>
    <main>
      <% if notice %>
        <blockquote>
          <%= notice %>
        </blockquote>
      <% end %>
      <% if alert %>
        <mark>
          <%= alert %>
        </mark>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/transactions/index.html.erb
<h1><%=t(:transactions)%></h1>

<% if START_DATE < 3.months.ago %>
  <div id="graph">
    <% @last_year_monthly_history.each_with_index do |monthly_value, index| %>
      <div id=<%= index.to_s + "-month-ago" %> class='month' style=<%= month_collumn_height_string(monthly_value) %>>
      </div>
    <% end %>
</div>
<% end %>

<div id="transactions">
  <% @transactions.each do |transaction| %>
    <% next if transaction.cancels_out && transaction.cancels_out.created_at < transaction.created_at %>
    <div class="transaction <%= 'cancelled' if transaction.cancels_out %>">
      <div id="date"> <%= transaction.created_at.to_date %> </div>
      <div id="amount">
        <%= transaction.deposit ? '+' : '-' %>
        <%= transaction.amount %>
      </div>
      <div id="comment"> <%= transaction.comment %> </div>
      <div id="executor"> <%= transaction.executor %> </div>
      <%= button_to "#{transaction.cancels_out ? t(:restore) : t(:revert)}", transaction, method: :delete %>
    </div>
  <% end %>
</div>

app/views/transactions/new.html.erb
<h1><%="#{@deposit ? t(:new_deposit) : t(:new_withdrawal)}"%></h1>

<%= form_with(model: @transaction) do |form| %>
  <% if @transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% @transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :deposit %>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div>
    <%= form.label :comment, style: "display: block" %>
    <%= form.text_area :comment %>
  </div>

  <div>
    <%= form.label :executor, style: "display: block" %>
    <%= form.text_field :executor, value: 'Julien' %>
  </div>

  <div>
    <%= form.label :secret_code, style: "display: block" %>
    <%= form.password_field :secret_code %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<br>